<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>OrbisPkgTool.Gui</AssemblyName>
    <RootNamespace>OrbisPkgTool.Gui</RootNamespace>
  </PropertyGroup>

</Project>
