<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="LibOrbisPkg.Core">
      <HintPath>C:\Users\User\source\repos\PS4PKGTool\Library.Core\LibOrbisPkg.Core.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

</Project>
